### ISSUE TITLE
[bug] VSCode Remote Repositories  not working

### ISSUE THREAD

**Issue by 2214962083** [zvizvi/GitHub-Web-IDE#11]
vscode version 1.66.0

click the button will open vscode, but nothing append after open vscode

**Comment by zvizvi** [comment]
Hi @ 2214962083, as you can see in issue #7, this option worked in the past, (as mentioned in [microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671](https://github.com/microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671) ).
It seems like it's not working anymore, so in the next update I'll remove it, until they fix it or maybe they'll come up with another solution...

**Comment by zvizvi** [comment]
Hi @2214962083,
As you can see in issue #7, this option worked in the past, (as mentioned in [microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671](https://github.com/microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671) ).
It seems like it's not working anymore, so in the next update I'll remove it, until they fix it or maybe they'll come up with another solution...

**Comment by 2214962083** [comment]
> Hi @2214962083,
> As you can see in issue #7, this option worked in the past, (as mentioned in [microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671](https://github.com/microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671) ).
> It seems like it's not working anymore, so in the next update I'll remove it, until they fix it or maybe they'll come up with another solution...

yes. it seems vscode extensions's bug, thanks to reply
