### ISSUE TITLE
edge addons store?

### ISSUE THREAD

**Issue by HAHH9527** [zvizvi/GitHub-Web-IDE#15]
https://microsoftedge.microsoft.com/addons/detail/github-web-ide/akjbkjciknacicbnkfjbnlaeednpadcf

The current version is still 2.0.1.
This version can't save setting.

**Comment by zvizvi** [comment]
Hi @HAHH9527. thanks for opening the issue.
I sent the last extension update to the Edge addons store about a week ago. I'm still waiting for them to approve it...

**Comment by HAHH9527** [comment]
@zvizvi thanks for your reply. Now I switched to chrome addons store.
Maybe you can add github repo url to description?
I found the repo by github searching.

**Comment by zvizvi** [comment]
That's a good idea, I'll do it.

**Comment by zvizvi** [comment]
The update has just appeared in the Edge addons store.

**Comment by HAHH9527** [comment]
Thank you for providing such a useful plugin.
