### ISSUE TITLE
cannot support new github

### ISSUE THREAD

**Issue by Billy1900** [zvizvi/GitHub-Web-IDE#39]
This web github IDE cannot support in new github version. The button does not appear.

**Comment by liuyib** [comment]
+1

**Comment by superdl1996** [comment]
+1

**Comment by kevin262516** [comment]
When i log in , there is no DOM node with the class name "file-navigation".

### not login
> ![image](https://github.com/zvizvi/GitHub-Web-IDE/assets/8156882/b10a4316-1489-4231-80cf-e5334bed4d91)

### login
> ![image](https://github.com/zvizvi/GitHub-Web-IDE/assets/8156882/a0c5d5c6-e1e8-45aa-9ae2-d8719f7427e3)


I tried to modify it, but I couldn't find the naming rules for classes.

Is there a better solution?

**Comment by Maxim-Mazurok** [comment]
I loved this one, was wondering why it stopped working...

I know github has `Ctrl + .` shortcut, but I don't like that github.dev doesn't use URL routing. I prefer github1s for this reason.
This extension seems to work for me now: https://chromewebstore.google.com/detail/shortcut-to-github1s/gfcdbodapcbfckbfpmgeldfkkgjknceo?hl=en-US&utm_source=ext_sidebar

Cheers!

**Comment by zvizvi** [comment]
Fixed in version 2.0.4 (0c7d19d08276108fe7f94f385bb19c4b8484a77e)

**Comment by texastoland** [comment]
Thank you @zvizvi I missed this 🎆
