### ISSUE TITLE
VS Code Remote Repositories extension

### ISSUE THREAD

**Issue by vlascik** [zvizvi/GitHub-Web-IDE#7]
MS and Github recently published [Remote Repositories](https://marketplace.visualstudio.com/items?itemName=github.remotehub) VS Code extension, which allows for opening GH repos without cloning first.

Do you think it would be possible to add the support for it to your extension too?

**Comment by yossizahn** [comment]
https://github.com/microsoft/vscode-remote-repositories-github/issues/5#issuecomment-861814671

**Comment by zvizvi** [comment]
I've done it now using the new Open VScode website [open.vscode.dev](https://open.vscode.dev).
